const actionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    TOGGLE_HIDDEN_DROPDOWN: 'TOGGLE_HIDDEN_DROPDOWN',
    ADD_ITEMS_TO_CART: 'ADD_ITEMS_TO_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
}


export default actionTypes;